language: node_js

node_js: "7"

install:
- npm install

script:
- npm test

env:
- NODE_ENV=test

cache:
  directories:
  - "node_modules"

services:
- postgresql


before_script:
- createuser more_recipe -s -U postgres
- createdb moreRecipeTest --username=postgres
- sequelize db:migrate

after_success: npm run coverage

notifications:
  webhooks: https://coveralls.io/webhook repo_token=Fdrh3aLsYA3PJOZhsgKJNCeZh3r0rJ4Ud